# Generated by Django 2.0.13 on 2019-07-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='cliente',
        ),
    ]
